### ISSUE TITLE
Support of target_precompile_headers

### ISSUE THREAD

**Issue by martin-s** [pavelliavonau/cmakeconverter#102]
If the VS project includes a pch, we could map it to cmake _[target_precompile_headers](https://cmake.org/cmake/help/latest/command/target_precompile_headers.html)_. It provides similar functionality and enables seamless build of the corresponding cmake project.

Example:
`target_precompile_headers($PROJECT_NAME PRIVATE "pc.h")`

**Comment by pavelliavonau** [comment]
I know it. I'm limited with 3.14 cmake from EPEL of centos 7. New features will be implemented in case of cmake upgrade in my case.

**Comment by martin-s** [comment]
Ok, got it. What about experimental features for environments which already provide cmake 3.16 and above?

**Comment by pavelliavonau** [comment]
What experimental features?
When I go upgrade minimal cmake I implement all useful stuff from release notes.

**Comment by martin-s** [comment]
I meant to introduce some experimental features for example with a new parameter:
`cmake_converter --x-pch`
But maybe a branch would be better.

**Comment by pavelliavonau** [comment]
I'm going to upgrade at once pch feature and minimal required version.
This software is not so complex enough to test features like experimental)
But why is it blocks you? Pch works fine for msvc now.

**Comment by martin-s** [comment]
Ok, don't mind. Can be closed.

**Comment by pavelliavonau** [comment]
@martin-s , check 1a753188acc1f5d04baa514aea05e2c18b5a73b3 from feature/pch branch

**Comment by pavelliavonau** [comment]
Implemented with 1a753188acc1f5d04baa514aea05e2c18b5a73b3 at develop
