### ISSUE TITLE
Introduce module parameter "configuration-filter"

### ISSUE THREAD

**Issue by martin-s** [pavelliavonau/cmakeconverter#103]
Like the projects-filter parameter, there should be a filter on configuration "Win32" or "x64" etc., so that from every project in the solution just a specific configuration is exported to cmake.

Example for filtering the x64 configurations:
`cmake_converter --solution=myproject.sln --configuration-filter=^x64$`

**Comment by pavelliavonau** [comment]
looks tricky. 
I rely on mapping from solution to projects and in general config names that mapped to each other could be different. 
I suppose that if files contain those configs they must be translated. If you want to remove them - do it with visual studio - it's very simple and quick.

**Comment by martin-s** [comment]
I cannot change the solution file. This is tricky for me ;-)
What about filtering with platform, e.g. Release|x64? If that makes the process simpler.
Will also have look into the code. But you are probably more into it than me.

**Comment by pavelliavonau** [comment]
1. I suppose that if files contain those configs they must be translated. (-p option is tricky and I do not like it)
2. You can easily ignore current unused configs at cmakelists.

Solving mapping between sln and proj is not clear. I wouldn't like to pollute my code with tricks like this
