### ISSUE TITLE
Crash on parsing <PrecompiledHeader> without Condition attr ($(Configuration)|$(Platform))

### ISSUE THREAD

**Issue by martin-s** [pavelliavonau/cmakeconverter#104]
When a precompiled header element contains no condition, parser fails and aborts.

See example solution:
[ConsoleApplication1.zip](https://github.com/pavelliavonau/cmakeconverter/files/4452511/ConsoleApplication1.zip)

`<PrecompiledHeader>Create</PrecompiledHeader>`

**Comment by pavelliavonau** [comment]
How did you create this example?
Provide the way of creating this without any manual editions. Use only Visual Studio UI.

**Comment by martin-s** [comment]
To create the example, I edited it manually.

**Comment by pavelliavonau** [comment]
The issue is wrong then.
I'm not going to fix issues that appears with manual editing. There might be too many cases like this. Every xml should be validated with visual studio. Otherwise this bug is invalid.

**Comment by martin-s** [comment]
Ok, I'm fine with that.
