### ISSUE TITLE
Support for CustomBuild items

### ISSUE THREAD

**Issue by The-42** [pavelliavonau/cmakeconverter#106]
Good day,

I am working on a project which uses a custom XML format to generate additional C headers. Those files are part of the project tree and appear in both project and filter files:

someProject.vcxproj:
```xml
<ItemGroup>
  <CustomBuild Include="params\params.pfxml">
    <FileType>XML</FileType>
    <SubType>Designer</SubType>
  </CustomBuild>
</ItemGroup>
```

someProject.vcxproj.filters:
```xml
<ItemGroup>
  <CustomBuild Include="params\params.pfxml">
    <Filter>common\params\interface</Filter>
  </CustomBuild>
</ItemGroup>
```

Right now, they are ignored (tested with the current `develop` branch). The actual build step is defined in a .props file as it is shared among multiple projects (within the same solution), but this is not a problem. I am after the inclusion of those files into the CMake source definitions, to be able to handle them easily with an `add_custom_command` line. This would require handling `CustomBuild` nodes, but not much more, I think.

**Comment by pavelliavonau** [comment]
Hello,
It's unclear for me what the <CustomBuild> is. Could you provide minimal example of solution for testing on my side?  But this example must be created from scratch only with visual studio UI (without any manual edition). Describe specific steps of creating this example if any.

**Comment by The-42** [comment]
Of course :) Recreating is easy (VS 2017):
- Create a new solution, say, a "Visual C++ Windows Console App".
- Add a new item to the project. I went for Web -> XML file, but it does not really matter.
- Go to the properties (right click -> Properties) of the new file, and set its item type to "Custom Build Tool". This makes VS think it has to process it through a "Custom Build Step", but you do not have to define it yet.

The resulting project is [this](https://github.com/pavelliavonau/cmakeconverter/files/4479194/ConsoleApplication1.zip), but the important parts are those:

*.vcxproj:
```xml
<ItemGroup>
  <CustomBuild Include="XMLFile.xml" />
</ItemGroup>
```

*.vcxproj.filters:
```xml
<ItemGroup>
  <CustomBuild Include="XMLFile.xml" />
</ItemGroup>
```
It does not matter whether an actual filter is set or not. With the current `develop` branch, the XML file does not show up after running `cmake-converter -s Solution1.sln` and the subsequent `cmake -S. -BPath\To\ConsoleApplication1\build -G"Visual Studio 15 2017 Win64"`. With !107, it does and it is also part of the related `CMakeLists.txt` :)

**Comment by pavelliavonau** [comment]
I tried to follow your instructions and on second point got next:

```
  <ItemGroup>
    <Xml Include="XMLFile.xml" />
  </ItemGroup>
```
Still can't achieve `<CustomBuild>` node with gui.
I use VS 2017 15.9.6

**Comment by The-42** [comment]
Your file still seems to has its file type set to _XML_ in Visual Studio. Change it via the property pages to _Custom Build_. Right click, go to _Properties_...
![2020-04-27 08_42_42-ConsoleApplication1 - Microsoft Visual Studio](https://user-images.githubusercontent.com/5832542/80342074-d4b51b00-8863-11ea-8218-ef2570f52325.png)
...and select _Custom Build Tool_ in the File Type list:
![2020-04-27 08_43_58-ConsoleApplication1 - Microsoft Visual Studio](https://user-images.githubusercontent.com/5832542/80342082-d7177500-8863-11ea-93f3-cc5f51153097.png)
Save the project and have at look at the .vcxproj - this does the trick for me. Tested with VS 2017 15.9.18.

**Comment by pavelliavonau** [comment]
adding following to the target:
```
set(xml
    "XMLFile.xml"
)
source_group("xml" FILES ${xml})
```

leads to 

`<XML Include="E:\projects\crash_pch\ConsoleApplicationXML\XMLFile.xml" />`

in generated solution. is it ok for you? Do you know how to force CMake to generate `<CustomBuild>` instead of `<Xml>` in this case?

if it's ok we can interprete CustomBuild files like "Other files".
