### ISSUE TITLE
Cmakelist - create several sln files

### ISSUE THREAD

**Issue by Eldadc** [pavelliavonau/cmakeconverter#113]
Hi,

I have a project where my sln and some other vcproj files are on the same root dir.
After running the converter the cmake list creats those vcproj files as projecta including the major sln file.
Is there a workaround to create those vcproj as targets and not sln.

Thanks

**Comment by pavelliavonau** [comment]
Hi @Eldadc ,

0. You must follow issue template and describe it properly.
1. You haven't mentioned version of cmake-converter.
2. Have you tried source from HEAD of develop?

**Comment by Eldadc** [comment]
Hi,
Thanks on the quick response.
Using 2.0.1. Vesrsion.
I did not understand #36 
Thanks

**Comment by pavelliavonau** [comment]
Why 36? 
It's closed. Any relations?

**Comment by Eldadc** [comment]
Hi,

What did you mean by
Have you tried source from HEAD of  develop ?

Thanks

**Comment by pavelliavonau** [comment]
I meant git head of develop branch.

**Comment by Eldadc** [comment]
Ok thanks.
So do you have an idea what do when the sln and other vcxproj are in the same root dir.

Thanks

**Comment by pavelliavonau** [comment]
How is it related to the bug?

I'm not going support about cmake for free.

**Comment by pavelliavonau** [comment]
Fixed with 16f2da3a693db2c6ef19601e6668a1df0f9bc571
