### ISSUE TITLE
Msys/Cygwin python poorly supported.

### ISSUE THREAD

**Issue by smaudet** [pavelliavonau/cmakeconverter#117]
Current source code works poorly in an msys environment (actual release seemed to work OK, compilation from recent source produces all manner of weird artifacts).

**To Reproduce**
Run Msys with python with a recent checkout ( 85e9c4d20e55b2dd06462c3754daebd9f801bb4b )

**Expected behavior**
File paths are found, conversion works at all...

**Additional context**
Large number of bogus paths found e.g. /c/my/path/c/my/path/file.vcproj

**Comment by pavelliavonau** [comment]
Well, haven't plans to support this. This could be low priority issue. Could be solved for a money reward.

**Comment by smaudet** [comment]
...I mean, its fair, I'm not asking you to support every possible environment/mix of things in the world, but you know...

When you are using `ntpath` liberally in your code what do you expect when the tiniest deviation causes stuff to go haywire?

Now with linux/msys2/cygwin/docker etc. the *simple* solution is to pretend C:/ doesn't exist as much as possible, do everything with relative-to-root + absolute pathing.

You don't have to support everything to do things in a manner that it works most places with minimal effort. This is just simple pathing, not like I'm asking for dynamic bytecode transformation on-the-fly like Apple does...
