### ISSUE TITLE
 Cannot determine link language for target "ConsoleApplication3"

### ISSUE THREAD

**Issue by sonygod** [pavelliavonau/cmakeconverter#122]
**Describe the bug**

-- Configuring done
CMake Error: Cannot determine link language for target "ConsoleApplication3".
CMake Error: CMake can not determine linker language for target: ConsoleApplication3

**To Reproduce**

 https://github.com/sonygod/doudizhuTest

**Expected behavior**

CMake Generate step failed.  Build files cannot be regenerated correctly.

visual stuido 2015 c++

ubuntu 18.04

cmake version 3.18.2

**Comment by pavelliavonau** [comment]
Did you investigate by yourself?
What the cmakelists are and what they should be?
