### ISSUE TITLE
Add support for Visual Studio 17 2022 generator

### ISSUE THREAD

**Issue by TEXflip** [pavelliavonau/cmakeconverter#146]
It is almost an year since the release of Visual studio 2022, it would be nice to have the support for converting their projects.

**Comment by pavelliavonau** [comment]
What is the issue with "Visual studio 2022" CMake generator?

**Comment by TEXflip** [comment]
I'm sorry, I just realized it was a cmake problem. I runned cmake generation after converting a VS2022 project and It doesn't have its generator. After a while I was thinkng about the problem I forgot that I runned cmake and not cmake-converter. 

I'm sorry again, you can remove the issue.
