### ISSUE TITLE
It's giving me this error, I'm trying to convert the GARbro project to cmake, but something wrong is happening.

### ISSUE THREAD

**Issue by Arthurfogo7** [pavelliavonau/cmakeconverter#148]
arthur@Arthur-PC:~$ cmake-converter -s /home/arthur/Downloads/GARbro/GARbro.sln
0.000053 processes count = 4
0.000081 warnings level = 2
0.020202 1> ERR  : Unknown project type at /home/arthur/Downloads/GARbro/Console/GARbro.Console.csproj
0.020312 2> ERR  : Unknown project type at /home/arthur/Downloads/GARbro/ArcFormats/ArcFormats.csproj
0.020424 3> ERR  : Unknown project type at /home/arthur/Downloads/GARbro/GameRes/GameRes.csproj
0.020506 4> ERR  : Unknown project type at /home/arthur/Downloads/GARbro/GUI/GARbro.GUI.csproj
0.020590 5> ERR  : Unknown project type at /home/arthur/Downloads/GARbro/Image.Convert/Image.Convert.csproj
0.020713 6> ERR  : /home/arthur/Downloads/GARbro/SchemeBuilder/SchemeBuilder.csproj project file doesn't exist ... skipping 
0.020941 8> ERR  : Unknown project type at /home/arthur/Downloads/GARbro/Legacy/Legacy.csproj
0.020955 9> ERR  : Unknown project type at /home/arthur/Downloads/GARbro/Net20/Net20.csproj
0.021427 7> ERR  : Unknown project type at /home/arthur/Downloads/GARbro/Experimental/Experimental.csproj
0.023673 Conversion of /home/arthur/Downloads/GARbro/GARbro.sln finished

Now you may run cmake like following samples:

to generate:
cmake -S "" -B "build" -G "Visual Studio 15 2017 Win64"
    or
cmake -S "" -B "build" -G "Visual Studio 16 2019" -A "x64"

to build:
cmake --build "build"

**Comment by pavelliavonau** [comment]
Have you read the readme at least?
cs projects are not supported
