### ISSUE TITLE
Question: From where to run the converter command?

### ISSUE THREAD

**Issue by DKGH** [pavelliavonau/cmakeconverter#150]
From where do I run this command:

```
cmake-converter -s <path/to/file.sln>
```

From anaconda prompt (where I ran the previous pip install command), I am getting the following error:

```
cmake-converter is not recognized as an internal or external command, operable program or batch file.
```

**Comment by pavelliavonau** [comment]
Check output of pip. Seems that installed location of utility is not in path. It might be in case pip used --user switch by default.

**Comment by DKGH** [comment]
Thanks
