### ISSUE TITLE
Only getting Debug build

### ISSUE THREAD

**Issue by DKGH** [pavelliavonau/cmakeconverter#151]
I am only seeing Debug build. I am using VS Code on Windows. I have the CMake Tools extension in VS Code. How do I get it to produce a Release build?

**Comment by pavelliavonau** [comment]
Dear, @DKGH,
Stop polluting this issue tracker with unrelated issues. 
Here is no support of pip (#150) or vscode (#151). Go and flood there next time when you have question about other tools.
