### ISSUE TITLE
Fix pep8 / pylint issues in new develop

### ISSUE THREAD

**Issue by algorys** [pavelliavonau/cmakeconverter#35]
Fix pep8 / pylint issues in new develop, add missing docstrings.

**Comment by pavelliavonau** [comment]
@algorys , Matt, are you available?) I am trying to contact you via skype and via email(sammalfor@gmail.com - seems that address doesn't work). Give me feedback, please.

**Comment by algorys** [comment]
@pavelliavonau please contact me on my commit mail address
