### ISSUE TITLE
paths issues on android(unix)

### ISSUE THREAD

**Issue by Mario1159** [pavelliavonau/cmakeconverter#79]
I converted my Visual Studio project to CMake and worked successfully on windows, however i'm trying to compile it in android using Cxxdroid app (which has cmake version 3.14).
It didn't work at first try because the include and link paths were making reference to my windows computer so i changed them but i still can't get it to work.
[With paths i refer to the includes of SFML and EnTT and the libs from SFML]

![WhatsApp Image 2019-06-18 at 17 59 35](https://user-images.githubusercontent.com/24532325/59724226-2548fa00-91f7-11e9-81ef-d7fae93b3223.jpg)
(File structure of my project)

https://pastebin.com/K6uhhZbi <- CMakeList file from where is my code and vcxproj
I changed the paths in the lines 44, 45, 166 and 170. Originally the paths were like the lines 49 and 50.

https://pastebin.com/KPMFZj4g -< CMakeList file from where my solution is

This is what i get from make VERBOSE=1 in Cxxdroid terminal

![WhatsApp Image 2019-06-18 at 19 22 59](https://user-images.githubusercontent.com/24532325/59726232-d56e3100-91fe-11e9-9445-0d55eb283f90.jpeg)

**Comment by pavelliavonau** [comment]
@Mario1159 ,
1. replace '\' ->'/' at #include directives.
2. Make proper include paths(trivial task).
Shall see then.

Looks like you haven't investigated much. It's bad. You take my time to teach you how to write crossplatform code. I have no time for this.
Think more next time before creating issue, please.

**Comment by Mario1159** [comment]
Thanks and sorry, i'm not familiar with cmake
