### ISSUE TITLE
Proposal: Enabling Ninja Build by changing set(CMAKE_VS_PLATFORM_NAME ... in root CMakeLists.txt

### ISSUE THREAD

**Issue by bigla** [pavelliavonau/cmakeconverter#82]
I have a suggestion:

Instead of
```cmake
 if(NOT CMAKE_VS_PLATFORM_NAME)
    set(CMAKE_VS_PLATFORM_NAME "x64")
 endif()
```
one could try to determine the architecture with: 

```cmake
 if(NOT CMAKE_VS_PLATFORM_NAME)
    if(MSVC AND (${CMAKE_SIZEOF_VOID_P} EQUAL 8))
        set(CMAKE_VS_PLATFORM_NAME "x64")
    elseif(MSVC AND (${CMAKE_SIZEOF_VOID_P} EQUAL 4))
        set(CMAKE_VS_PLATFORM_NAME "Win32")
    else()
        message(SEND_ERROR "MSVC is ${MSVC} and CMAKE_SIZEOF_VOID_P is ${CMAKE_SIZEOF_VOID_P} ")
    endif()
 endif()
```
I am currently working on enabling the use of Ninja generator (while still using MSBuild environment) for my converted project, to speed up the build. I believe there is not much more to do.

**Comment by bigla** [comment]
I feared this would assume the Host System to be the same arch as the Target system but according to [CMake Manual](https://cmake.org/cmake/help/latest/variable/CMAKE_SIZEOF_VOID_P.html)
> CMAKE_SIZEOF_VOID_P
> Size of a void pointer.
> This is set to the size of a pointer on the **target machine**, and is determined by a **try compile**. If a 64-bit size is found, then the library search path is modified to look for 64-bit libraries first.

**Comment by pavelliavonau** [comment]
@bigla, I don't understand what problem do you have with Ninja generator at this case. Explain me, please.

**Comment by bigla** [comment]
The problem is here, that cmake-converter assumes that every project is on x64 architecture if CMAKE_VS_PLATFORM_NAME is not set. 

VS_PLATFORM_NAME seems to be set by MSBuild, but not Ninja.

During conversion there are several uses of `${CMAKE_VS_PLATFORM_NAME}` I would suggest to determine the platform architecture as shown above, using the `${CMAKE_SIZEOF_VOID_P}` value.

**Comment by pavelliavonau** [comment]
No problem here.
CMAKE_VS_PLATFORM_NAME is not depend on generator type. For vs generator it is set automatically but for ninja and others may be passed with cmd line

**Comment by pavelliavonau** [comment]
Using CMAKE_SIZEOF_VOID_P wrong with cross compiling. User must determine target architecture by himself. The best way to pass CMAKE_VS_PLATFORM_NAME during cmake configure stage

**Comment by bigla** [comment]
So you suggest I should just pass it with `-DCMAKE_VS_PLATFORM_NAME=x64` - is this how you meant it?

Further explanation:
I am working on migrating a visual studio project to ninja+clang-cl and linux+make+gcc  ... this is why I try to avoid CMAKE_VS_PLATFORM_NAME (which obviously will never exist on linux with make and gcc).

But i will try passing the CMAKE_VS_PLATFORM_NAME via cmdline in future although it seems strange to have something called `Win32` when compiling on Linux ;)

**Comment by bigla** [comment]
> Using CMAKE_SIZEOF_VOID_P wrong with cross compiling.

Are you sure?

I just noticed: 
When compiling with `gcc` : `CMAKE_SIZEOF_VOID_P == 8`
When compiling with `gcc -m32` : `CMAKE_SIZEOF_VOID_P == 4`

So `CMAKE_SIZEOF_VOID_P` shows **target** architecture - not **host** architecture and should be perfectly fine to determine the correct architecture.

[CMake Documentation](https://cmake.org/cmake/help/latest/variable/CMAKE_SIZEOF_VOID_P.html) says:
> This is set to the size of a pointer on the **target** machine

**Comment by pavelliavonau** [comment]
@bigla, check readme of this project and find main goal of it. Porting to Linux is not the objective of cmake converter. Even it's almost impossible programically! 
Cmakeconverter converts only from sln into cmake. That's lt.
CMAKE_VS_PLATFORM_NAME - just a name. Like win32 as well. I'm not going to rename it just for you. If you don't like win32 you may rename arch at solution and convert with 'better' names.

Arch at solution is target arch. And should be set by user on configure stage. Default value is x64 because vs chooses this arch by default when opening project first time. I also don't see the reason to change this.

Any additions?)

**Comment by bigla** [comment]
> Porting to Linux is not the objective of cmake converter. Even it's almost impossible programically!
I agree. 
I saw the opportunity to make it easier for people who try to support both platforms by wrapping Windows/MSVC-Only code in if(MSVC) or if(WIN32) clauses where necessary. Sorry I won't bother you with this in future.

> I'm not going to rename it just for you.
It is your project, you decide - I just made a suggestion.

> Arch at solution is target arch. And should be set by user on configure stage.
I see, you are right.

> Any additions?
Thank you for your time!

**Comment by pavelliavonau** [comment]
> I saw the opportunity to make it easier for people who try to support both platforms by wrapping Windows/MSVC-Only code in if(MSVC) or if(WIN32) clauses where necessary. Sorry I won't bother you with this in future.

I understand your intention and I'm trying to do the same. But I avoid to make cmake code too complex. We need to find balance at any activity and your change with CMAKE_SIZEOF_VOID_P are too complex and hard to my mind. Not useful enough to apply them.

I appreciate your contributing. Thank you too.
