### ISSUE TITLE
Release 1.2.0 is not on published on pypi

### ISSUE THREAD

**Issue by Croydon** [pavelliavonau/cmakeconverter#83]
Any specific reason for that?

**Comment by pavelliavonau** [comment]
No specific reason. @algorys ,maybe forgotten?

**Comment by pavelliavonau** [comment]
@Croydon , version 1.2.0 is just published. But it's too outdated. It's better to install from sources.

**Comment by pavelliavonau** [comment]
@Croydon , I've just published developer release on pypi 2.0.0.dev15072019 
do
pip install --pre cmake_converter

**Comment by Croydon** [comment]
Thanks!
