### ISSUE TITLE
<DelayLoadDLLs> is ignored.

### ISSUE THREAD

**Issue by bigla** [pavelliavonau/cmakeconverter#89]
When analyzing my built executable with DependenciesGui.exe I noticed that some external Libraries were not loaded with delay. (Delayed Loading : False )

Example XML:
```xml
...
  <ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Debug|Win32'">
    <ClCompile>
...
    </ClCompile>
    <ProjectReference>
      <LinkLibraryDependencies>true</LinkLibraryDependencies>
      <UseLibraryDependencyInputs>false</UseLibraryDependencyInputs>
    </ProjectReference>
    <Link>
      <DelayLoadDLLs>somelib.dll;otherlib.dll</DelayLoadDLLs>
    </Link>
...
```
No /DELEAYLOAD found in CMakeLists.txt but
Expected:
```cmake
if(MSVC)
  target_link_options(${PROJECT_NAME} PRIVATE
    $<$<CONFIG:Debug>:
      /DELAYLOAD:somelib.dll;
      /DELAYLOAD:otherlib.dll;
    >
  ) 
endif()?
```

I hope occurences of empty tags:
```xml
      <DelayLoadDLLs>
      </DelayLoadDLLs>
```
won't interfere with producing correct results. 

For future reference and anyone interested:
For `/DELAYLOAD` to work with Ninja `"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\lib\delayimp.lib"` needs to be linked to the target. (Make sure you started a developer console with the following snippet)

```batch
REM x86 or x86_64 or ... And adjust paths
CALL "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
SET "ADDITIONAL_PATH=D:/ninja-win;;%PROGRAMFILES(X86)%\Microsoft SDKs\Windows\v7.1A\Bin"
SET "PATH=%ADDITIONAL_PATH%;%PATH%"
```

Now you can use the following in your CMakeLists.txt:

```cmake
    string(CONCAT ADDITIONAL_LIBRARY_DEPENDENCIES
        "$<$<PLATFORM_ID:Windows>:"
            "delayimp;"
        ">"
```

**Comment by pavelliavonau** [comment]
@bigla, consider to make a donation ;)

**Comment by bigla** [comment]
I will pay something from my own pocket when everything is finished - I might also ask some other people. Until then I assume contribution in form of testing helps a little bit too :) ... someday I might even be good enough in programming python, that I might open pull requests to resolve issues. How does that sound?

**Comment by bigla** [comment]
I forgot one more thing: Thank you very much!

**Comment by pavelliavonau** [comment]
Sounds good. Thanks

**Comment by bigla** [comment]
> @bigla, consider to make a donation ;)

@pavelliavonau Done. :)
