### ISSUE TITLE
not all source files output to CMakeLists.txt

### ISSUE THREAD

**Issue by umarmohammed** [pavelliavonau/cmakeconverter#92]
I'm running cmake-converter with the -p option to generate a CMakeLists.txt file from a visual studio project file. However not all the source files are output in the resulting CMakeLists.txt file. 

I installed cmake-converter using `pip install cmake-converter`. I think this uses the version that is in the master branch.

I don't have any experience in Python, I even struggled to pull down and run the code. However after getting it running I think there may be a bug in project_files.py in the master branch. I think that

```self.sources = {cpp_path: []}``` should be ```self.sources[cpp_path] = []``` and
```self.headers = {header_path: []}``` should be ```self.headers[header_path] = []```

I realise that this has probably been fixed in the develop branch, however since the master branch is the one that is published to pip would it be possible to include a fix for this and update pip?

If this is indeed a bug and you guys are willing to update I'm happy to submit a pull request.

**Comment by pavelliavonau** [comment]
Use --pre release version instead. Code from develop is going to be released soon.

**Comment by umarmohammed** [comment]
Cool thanks. So I'll ```pip install cmake-converter --pre release```? To get the develop branch?

**Comment by pavelliavonau** [comment]
Yes. Check correspondent tag on develop branch to get version of code

**Comment by pavelliavonau** [comment]
Read the readme and make a donation)
