### ISSUE TITLE
version 1.2.0: Files Under Project Property Filters Mishandled

### ISSUE THREAD

**Issue by ChrisDrozdowski** [pavelliavonau/cmakeconverter#94]
Files listed under filters in project properties are not handled properly.

Given this Headers Files section in project properties (`Example Headers` and `orglab_cpp Headers` are filters):

Note: How to best provide an example project?

```
Header Files
|
|-Example Headers
|    |-example_utils.hpp
|    |-iterators.hpp
|    |-read.hpp
|    |-threaded_write.hpp
|    \-write.hpp
|
\-orglab_cpp Headers
     |-all.h
     |-orglab_cpp.hpp
     |-...
     \-orglab_cpp_column.hpp
```

The output is:
```
# Header Files
set(HEADERS_FILES
     read.hpp
     threaded_write.hpp
     write.hpp
)
```

**Comment by pavelliavonau** [comment]
Attach link to zip of example.
Attach verbose log of conversion.

**Comment by ChrisDrozdowski** [comment]
Actually I find that this has nothing to do with filters.

The issue is that, if some header files are in file system subfolders at the project level and some are at the project level, the headers in the subfolders don't get added to the CMakeLists.txt file. I did not test whether this applies to Source code files or not.

The zip file contains an example solution (it uses simple generic files not related to the example above) that will illustrate the issue. Also included in the zip file is the console output from running cmake-converter.

http://code.dented-planet.net/cmakeconv_issue.zip

**Comment by pavelliavonau** [comment]
@ChrisDrozdowski, You are using old code from stable release. It's too outdated and you should try to install from sources of develop branch. Read the Readme and follow completely before creating issue

**Comment by ChrisDrozdowski** [comment]
Sorry. Indeed I should have read Readme a bit better.

Issue is fixed in development branch.

**Comment by pavelliavonau** [comment]
Closes due new stable release.
