### ISSUE TITLE
NameError: name 'cmake' is not defined

### ISSUE THREAD

**Issue by eakarpov** [pavelliavonau/cmakeconverter#96]
cmake is installed on the computer, but the cli interface of cmake-converter gives the following error: "NameError: name 'cmake' is not defined"

**Comment by pavelliavonau** [comment]
What?

**Comment by eakarpov** [comment]
What am I doing not right?
![Screenshot from 2020-02-11 16-38-18](https://user-images.githubusercontent.com/16017789/74241363-f08d3400-4cec-11ea-96b7-57bdcf46d5f9.png)

**Comment by pavelliavonau** [comment]
Учи матчасть. Ты не понимаешь что делаешь. Конвертер от cmake не зависит. То что ты показал - полная дичь

**Comment by eakarpov** [comment]
Я не питонист. Я хотел лишь воспользоваться утилитой для преобразования кода проекта. Как я могу избавиться от ошибки, которую выдает конвертер? Что за имя "cmake" тогда, которое не определено?

**Comment by pavelliavonau** [comment]
1. Вся необходимая информация в ридми.
2. Не пользоваться ридми - не уважение.
3. Твои действия неадекватны и показывают полное не понимание ситуации. Подумай о смене профессии.

Ну и если тебе это поможет...

http://letmegooglethat.com/?q=How+to+run+a+python+script%3F
