### ISSUE TITLE
no support for .props files ?

### ISSUE THREAD

**Issue by kcris** [pavelliavonau/cmakeconverter#98]
.props files are similar to .vcxproj files but can be used (aka included) across multiple vcxproj files to <share> project settings.

All the variables I used in a .props file are not parsed and therefore not available in the .vcxproj files while using cmakeconverter.

thanks

**Comment by pavelliavonau** [comment]
Did you read the docs??
Props should be ported manually.

**Comment by pavelliavonau** [comment]
@kcris,
I added doc section about props files.
Answering to your question: No, it is no support of conversion of props files.
There is no appropriate solution to perform this automatically due difference of languages (msbuild and CMake). So try to implement them manually or get rid of them.

**Comment by DBraun** [comment]
My sln had a reference to `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\BuildCustomizations\CUDA 10.1.props`. `CUDA 10.1.cmake` doesn't exist, so I'm having a problem as you have described in the docs. What does it mean to implement the .cmake manually based on a .props file? Can you share an article that explains this subject? Thank you.

**Comment by pavelliavonau** [comment]
@DBraun , it means translate msbuild language to cmake terms. Check use_props function. You have target and config variables at cmake props and may use them. Some things might be impossible. I suggest to get rid of props because it's not CMake way. About article - maybe, if I find time for this.
